--- #YAML:1.0
name:               Async-ORM
version:            0.501
abstract:           Asynchronous Object-relational mapping
author:
    - Viacheslav Tikhanovskii <vti@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Any::Moose:    0
    Async::Hooks:  0
    DBI:           0
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
